### ISSUE TITLE
ox_target, no id 

### ISSUE THREAD

**Issue by KetoPz** [Thummie/thommie-arcade#1]
I have a error using ox_target: "No entity with id '...' exists", basically doesn't recognize the props given in client. pls help
![image](https://github.com/Thummie/thommie-arcade/assets/108960934/8d57c050-384e-46db-a200-c75b42eaa9b0)

**Comment by Thummie** [comment]
@KetoPz I have changed the code a bit and it should work from now, I am currently not home so I can't check if it is working but it should work again.
